### ISSUE TITLE
Codec, Decoder, and Encoder are !Send + !Sync

### ISSUE THREAD

**Issue by ExoticMatter** [vorner/tokio-serde-cbor#1]
Because Decoder and Encoder contain a `PhantomData<*const Item>` field, all three structs are `!Send + !Sync`. This prevents any of them from being used with a thread pool. Shouldn't the phantom data just be `PhantomData<Item>`? Neither the encoder nor the decoder have an internal state, as they simply read whole items from or write whole items to a buffer provided by the caller.

**Comment by vorner** [comment]
Thank you for reporting. It should be fixed in the 0.3.1 I just released.

Anyway, it should probably be `PhantomData<fn() -> Item>` and `PhantomData<fn(Item)` because it doesn't contain it, it gets one or produces one.
