### ISSUE TITLE
How do I use this codec?

### ISSUE THREAD

**Issue by najamelan** [vorner/tokio-serde-cbor#2]
Hi,

I'm trying to use this for ipc, but I can't get it to work, and found no examples or doc, or unit tests that show how this works with tokio streams... I can't figure out how I should use this. The code almost identical works with a LinesCodec (without using serde, just sending strings). 

This is what I got: https://github.com/najamelan/test_uds_tokio/blob/DecodeError/src/libpeers/ipc_peer.rs

Basically the codec gets setup in the new method.
The reading happens in the listening method.
The writing happens in the Handler<IpcMessage> impl. 
IpcMessage is a simple struct that derives serde Serialize/Deserialize. 

If you want to run it, use `cargo run --bin peera`. peerb.rs does the sending. peera.rs the receiving end.

I always get this error:
```rust
Error extracting IpcMessage from stream
Cbor(
    ErrorImpl {
        code: Message(
            "invalid type: byte array, expected struct IpcMessage"
        ),
        offset: 0
    }
)
```

Thanks in advance for your help.

**Comment by najamelan** [comment]
So I managed to get it working with the example in the pull request but it still doesn't work in my code. I'm afraid there might be some compatibility issues as I use futures 0.3 and tokio-async-await and family...

**Comment by najamelan** [comment]
I am trying to pinpoint the error, and by now I have something working that is really almost the same as the failing project, so don't bother looking into this. I will find it soon.

**Comment by najamelan** [comment]
Ok, the same commit that was failing last night now just works... what a waste of time! Sorry about this.

**Comment by vorner** [comment]
Sorry, I don't have the time to look into it right now ‒ but I hope I'll find the time during the coming weekend.

Anyway, futures 0.3 are not really supported yet.

**Comment by najamelan** [comment]
@vorner, don't worry, the bug somehow mysteriously dissapeared, even though git claims it's exactly the same code... go figure

**Comment by najamelan** [comment]
I figured it out at last. Actually I have 2 binaries in the project and the first launches the second to test  ipc communication. When running `cargo run --bin peera`, cargo won't rebuild peerb, so that binary will be stale... So breakage on the channel....duh
